mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name = 'enquetes'
urlpatterns = [
    path('', views.index, name="index"),
    path("<int:pergunta_id>/", views.detalhes, name="detalhes"),
    path("<int:pergunta_id>/resultados/", views.resultados, name="resultados"),
    path("<int:pergunta_id>/votos/", views.votos, name="votos"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls'))
]

# add at the last
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
    texto_pergunta = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField("date published")
    
    def __str__(self):
        return self.texto_pergunta

    def foi_publicado_recentemente(self):
        return self.data_publicacao >= timezone.now() - datetime.timedelta(days=1)


class Escolha(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto_escolha = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_escolha

mysite/enquetes/views.py
from django.db.models import F
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Pergunta, Escolha
from django.urls import reverse

def index(request):
    ultimas_perguntas = Pergunta.objects.order_by('-data_publicacao')[:5]
    contexto = { 'ultimas_perguntas': ultimas_perguntas }
    return render(request,'enquetes/index.html',contexto)

def detalhes(request,pergunta_id):
    try:
        pergunta = Pergunta.objects.get(pk=pergunta_id)
    except:
        raise Http404("A pergunta não existe!")
    return render(request, 'enquetes/detalhes.html',{'pergunta': pergunta})

def resultados(request,pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, "enquetes/resultados.html", {"pergunta": pergunta})

def votos(request,pergunta_id):
        pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
        try:
            escolha_selecionada = pergunta.escolha_set.get(pk=request.POST["escolha"])
        except (KeyError, Escolha.DoesNotExist):
            # Redisplay the question voting form.
            return render(  
                request,
                "enquetes/detalhes.html",
                {
                    "question": pergunta,
                    "error_message": "Você não selecionou uma escolha.",
                },
            )
        else:
            escolha_selecionada.votos = F("votos") + 1
            escolha_selecionada.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse("enquetes:resultados", args=(pergunta.id,)))

mysite/enquetes/templates/enquetes/detalhes.html
<form action="{% url 'enquetes:votos' pergunta.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ pergunta.texto_pergunta }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for escolha in pergunta.escolha_set.all %}
            <input type="radio" name="escolha" id="escolha{{ forloop.counter }}" value="{{ escolha.id }}">
            <label for="escolha{{ forloop.counter }}">{{ escolha.texto_escolha }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Votar">
</form>

mysite/enquetes/templates/enquetes/index.html
{% if ultimas_perguntas %}
    <ul>
    {% for pergunta in ultimas_perguntas %}
        <li><a href="{% url 'enquetes:detalhes' pergunta.id %}">{{ pergunta.texto_pergunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Sem enquetes disponíveis.</p>
{% endif %}

mysite/enquetes/templates/enquetes/resultados.html
<h1>{{ pergunta.texto_pergunta }}</h1>

<ul>
{% for escolha in pergunta.escolha_set.all %}
    <li>{{ escolha.texto_escolha }} -- {{ escolha.votos }} voto{{ escolha.votospluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'enquetes:detalhes' pergunta.id %}">Quer votar novamente?</a>